# SPDX-License-Identifier: MIT
file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")
function(run_case name expected)
  execute_process(COMMAND "${BEAUTIZE}" ${ARGN}
    WORKING_DIRECTORY "${WORK}" RESULT_VARIABLE code OUTPUT_VARIABLE output ERROR_VARIABLE error)
  file(WRITE "${WORK}/${name}.log" "exit=${code}\n${output}\n${error}")
  if(NOT "${code}" STREQUAL "${expected}")
    message(FATAL_ERROR "${name}: expected exit ${expected}, got ${code}\n${output}\n${error}")
  endif()
  message(STATUS "PASS ${name}")
endfunction()
run_case(help 0 --help)
run_case(dry_run 0 "${SOURCE}/examples/ethanol_clash.gjf" --dry-run -o dry.gjf)
if(EXISTS "${WORK}/dry.gjf" OR EXISTS "${WORK}/dry.json")
  message(FATAL_ERROR "Dry run wrote outputs")
endif()
run_case(water 0 "${SOURCE}/examples/water_frozen.gjf" -o water.gjf --xyz water.xyz --trajectory water.traj.xyz)
file(READ "${WORK}/water.json" report)
string(JSON converged GET "${report}" converged)
string(JSON drift GET "${report}" frozen_max_absolute_component_drift_angstrom)
if(NOT converged OR NOT drift EQUAL 0)
  message(FATAL_ERROR "Invalid water result JSON")
endif()
if(EXISTS "${WORK}/gfnff_topo")
  message(FATAL_ERROR "CLI unexpectedly wrote a GFN-FF topology cache")
endif()
file(SHA256 "${WORK}/water.gjf" before)
run_case(no_clobber 1 "${SOURCE}/examples/water_frozen.gjf" -o water.gjf)
file(SHA256 "${WORK}/water.gjf" after)
if(NOT before STREQUAL after)
  message(FATAL_ERROR "Existing output changed despite overwrite protection")
endif()
run_case(no_source_overwrite 1 "${SOURCE}/examples/water_frozen.gjf" -o "${SOURCE}/examples/water_frozen.gjf" --overwrite)
run_case(output_alias 1 "${SOURCE}/examples/water_frozen.gjf" -o alias.gjf --report alias.gjf)
run_case(modr 0 "${SOURCE}/examples/water_modr.gjf" -o modr.gjf)
run_case(ethanol_clash 0 "${SOURCE}/examples/ethanol_clash.gjf" -o ethanol.gjf)
run_case(explicit_targets 0 "${SOURCE}/examples/water_frozen.gjf" --bond 1,2=1.0 --angle 2,1,3=110 -o targeted.gjf)
run_case(mobile_complement 0 "${SOURCE}/examples/water_frozen.gjf" --mobile 2-3 -o mobile.gjf)
file(WRITE "${WORK}/extra.constraints" "! Extra constraints\nB 1 2 F\nA 2 1 3 F\n")
run_case(constraint_file 0 "${SOURCE}/examples/water_frozen.gjf" --constraints extra.constraints -o external.gjf)
file(READ "${SOURCE}/examples/water_frozen.gjf" nofreeze)
string(REPLACE "-1" " 0" nofreeze "${nofreeze}")
file(WRITE "${WORK}/no_freeze.gjf" "${nofreeze}")
run_case(refuse_unconstrained 1 no_freeze.gjf -o no_freeze_output.gjf)
if(EXISTS "${WORK}/no_freeze_output.gjf")
  message(FATAL_ERROR "Unconstrained output was created without consent")
endif()
run_case(allow_unconstrained 0 no_freeze.gjf --allow-unconstrained -o allowed.gjf)
file(READ "${SOURCE}/examples/water_modr.gjf" badmodr)
string(REPLACE "B 1 2 F" "B 1 2 S 4 0.1" badmodr "${badmodr}")
file(WRITE "${WORK}/scan.gjf" "${badmodr}")
run_case(reject_scan 1 scan.gjf -o scan_out.gjf)
run_case(explicit_ignore 0 scan.gjf --ignore-gjf-constraints --freeze 1 -o ignored.gjf)
run_case(max_steps 2 "${SOURCE}/examples/water_frozen.gjf" --max-steps 0 -o unfinished.gjf)
if(EXISTS "${WORK}/unfinished.gjf")
  message(FATAL_ERROR "Nonconverged output was published as a normal result")
endif()
file(READ "${WORK}/unfinished.json" report)
string(JSON converged GET "${report}" converged)
if(converged)
  message(FATAL_ERROR "Nonconvergence incorrectly reported as success")
endif()
run_case(keep_partial 2 "${SOURCE}/examples/water_frozen.gjf" --max-steps 0 --keep-partial -o partial.gjf)
if(NOT EXISTS "${WORK}/partial.partial.gjf" OR EXISTS "${WORK}/partial.gjf")
  message(FATAL_ERROR "Partial result naming is incorrect")
endif()
run_case(conflicting_constraint 1 "${SOURCE}/examples/water_modr.gjf" --bond 1,2=2.0 -o conflict.gjf)
run_case(all_frozen 0 "${SOURCE}/examples/water_modr.gjf" --freeze 1-3 -o all_frozen.gjf)
run_case(gnu_attached_values 0 "${SOURCE}/examples/water_frozen.gjf" --freeze=1 --bond=1,2=1.0 --angle=2,1,3=110 --threads=1 --output=attached.gjf)
run_case(reject_flag_value 1 "${SOURCE}/examples/water_frozen.gjf" --quiet=true -o bad_flag.gjf)
run_case(quiet 0 "${SOURCE}/examples/water_frozen.gjf" --quiet -o quiet.gjf)
if(EXISTS "${WORK}/gfnff_topo")
  message(FATAL_ERROR "Topology cache leaked into working directory")
endif()
message(STATUS "22 CLI integration scenarios passed")
